

package lo23.ui.grid;

import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import lo23.data.ApplicationModel;
import lo23.data.Player;
import lo23.data.PublicProfile;
import lo23.utils.Enums.STATUS;

/**
 * Create box with the name, age and avatar
 * @author lopicave
 */
public class PlayerPanel extends javax.swing.JPanel {
    ApplicationModel myModel;
    public static final java.awt.Color fond = new java.awt.Color(170, 51, 0);
    
        /** Creates new form PlayerPanel */
    public PlayerPanel(ApplicationModel model, Player player,String image) {
        initComponents();
        myModel = model;
        // inits values
        nickName.setText(player.getPublicProfile().getPseudo());
        age.setText(String.valueOf(player.getPublicProfile().getAge()) + " ans");
        


     
     if(player.getPublicProfile().getAvatar()==null)
     {
         avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource(image))); // NOI18N
     }
     else
     {
          avatar.setIcon(player.getPublicProfile().getAvatar());
     }

     this.setOpaque(false);
     this.setBorder(BorderFactory.createTitledBorder(""));
    // this.setBorder(border);
    }

    public PlayerPanel(ApplicationModel model) {
        initComponents();
        myModel = model;
        // inits values
      //  age.setText(String.valueOf(player.getPublicProfile().getAge()));
      //  nickName.setText(player.getPublicProfile().getPseudo());

        //ImageIcon img = player.getPublicProfile().getAvatar();
       // Icon ico = new ImageIcon(img);
       // avatar.setIcon(ico);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avatar = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        nickName = new javax.swing.JLabel();

        avatar.setBackground(new java.awt.Color(51, 255, 51));

        age.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setText("Age");

        nickName.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        nickName.setForeground(new java.awt.Color(139, 23, 23));
        nickName.setText("Avoir un grand nom");
        nickName.setToolTipText("");
        nickName.setMaximumSize(new java.awt.Dimension(50, 23));
        nickName.setMinimumSize(new java.awt.Dimension(0, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(age)
                        .addGap(47, 70, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nickName, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nickName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(age)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JLabel avatar;
    private javax.swing.JLabel nickName;
    // End of variables declaration//GEN-END:variables

}
